# Generated by Django 5.0.2 on 2024-07-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='installcmd',
            field=models.CharField(default='', max_length=255),
        ),
    ]
